sudo: required
services:
  - docker

before_install:
  - docker build -t mrcbo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mrcbo/react-test npm test -- --coverage

after_success:
  - docker build -t mrcbo/multi-client ./client
  - docker build -t mrcbo/multi-nginx ./nginx
  - docker build -t mrcbo/multi-server ./server
  - docker build -t mrcbo/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mrcbo/multi-client
  - docker push mrcbo/multi-nginx
  - docker push mrcbo/multi-server
  - docker push mrcbo/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: foobars
  env: Foobars-env
  bucket_name: elasticbeanstalk-us-east-1-711552313519
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
